language: android
jdk:
  # For retrolambda
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

before_install:
  - sudo pip install codecov

after_success:
  - ./gradlew jacocoTestReport
  - cp ./app/build/reports/jacocoTestReport/*.xml jacoco.xml
  - cp ./app/build/reports/jacocoTestReport/*.xml jacoco2.xml
  - codecov
